# Generated by Django 4.1.6 on 2023-02-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_supplier_inventory_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
    ]
