# Generated by Django 4.1.6 on 2023-02-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
