# Generated by Django 4.1.6 on 2023-02-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
